// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"github.com/google/uuid"
	"github.com/noellimx/go-ddd/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Create(product *entities.ValidatedProduct) (*entities.Product, error) {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) (*entities.Product, error)); ok {
		return returnFunc(product)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) *entities.Product); ok {
		r0 = returnFunc(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.ValidatedProduct) error); ok {
		r1 = returnFunc(product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - product *entities.ValidatedProduct
func (_e *MockProductRepository_Expecter) Create(product interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", product)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(product *entities.ValidatedProduct)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.ValidatedProduct
		if args[0] != nil {
			arg0 = args[0].(*entities.ValidatedProduct)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(product1 *entities.Product, err error) *MockProductRepository_Create_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(product *entities.ValidatedProduct) (*entities.Product, error)) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Delete(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) Delete(id interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(err error) *MockProductRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(id uuid.UUID) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindAll() ([]*entities.Product, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entities.Product, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entities.Product); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockProductRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockProductRepository_Expecter) FindAll() *MockProductRepository_FindAll_Call {
	return &MockProductRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockProductRepository_FindAll_Call) Run(run func()) *MockProductRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProductRepository_FindAll_Call) Return(products []*entities.Product, err error) *MockProductRepository_FindAll_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepository_FindAll_Call) RunAndReturn(run func() ([]*entities.Product, error)) *MockProductRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindById(id uuid.UUID) (*entities.Product, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*entities.Product, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *entities.Product); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockProductRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) FindById(id interface{}) *MockProductRepository_FindById_Call {
	return &MockProductRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockProductRepository_FindById_Call) Run(run func(id uuid.UUID)) *MockProductRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_FindById_Call) Return(product *entities.Product, err error) *MockProductRepository_FindById_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_FindById_Call) RunAndReturn(run func(id uuid.UUID) (*entities.Product, error)) *MockProductRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Update(product *entities.ValidatedProduct) (*entities.Product, error) {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) (*entities.Product, error)); ok {
		return returnFunc(product)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) *entities.Product); ok {
		r0 = returnFunc(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.ValidatedProduct) error); ok {
		r1 = returnFunc(product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - product *entities.ValidatedProduct
func (_e *MockProductRepository_Expecter) Update(product interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", product)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(product *entities.ValidatedProduct)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.ValidatedProduct
		if args[0] != nil {
			arg0 = args[0].(*entities.ValidatedProduct)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(product1 *entities.Product, err error) *MockProductRepository_Update_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(product *entities.ValidatedProduct) (*entities.Product, error)) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
