// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"github.com/google/uuid"
	"github.com/noellimx/go-ddd/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSellerRepository creates a new instance of MockSellerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSellerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSellerRepository {
	mock := &MockSellerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSellerRepository is an autogenerated mock type for the SellerRepository type
type MockSellerRepository struct {
	mock.Mock
}

type MockSellerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSellerRepository) EXPECT() *MockSellerRepository_Expecter {
	return &MockSellerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSellerRepository
func (_mock *MockSellerRepository) Create(seller *entities.ValidatedSeller) (*entities.Seller, error) {
	ret := _mock.Called(seller)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Seller
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedSeller) (*entities.Seller, error)); ok {
		return returnFunc(seller)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedSeller) *entities.Seller); ok {
		r0 = returnFunc(seller)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Seller)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.ValidatedSeller) error); ok {
		r1 = returnFunc(seller)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSellerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSellerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - seller *entities.ValidatedSeller
func (_e *MockSellerRepository_Expecter) Create(seller interface{}) *MockSellerRepository_Create_Call {
	return &MockSellerRepository_Create_Call{Call: _e.mock.On("Create", seller)}
}

func (_c *MockSellerRepository_Create_Call) Run(run func(seller *entities.ValidatedSeller)) *MockSellerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.ValidatedSeller
		if args[0] != nil {
			arg0 = args[0].(*entities.ValidatedSeller)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSellerRepository_Create_Call) Return(seller1 *entities.Seller, err error) *MockSellerRepository_Create_Call {
	_c.Call.Return(seller1, err)
	return _c
}

func (_c *MockSellerRepository_Create_Call) RunAndReturn(run func(seller *entities.ValidatedSeller) (*entities.Seller, error)) *MockSellerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSellerRepository
func (_mock *MockSellerRepository) Delete(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSellerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSellerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockSellerRepository_Expecter) Delete(id interface{}) *MockSellerRepository_Delete_Call {
	return &MockSellerRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockSellerRepository_Delete_Call) Run(run func(id uuid.UUID)) *MockSellerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSellerRepository_Delete_Call) Return(err error) *MockSellerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSellerRepository_Delete_Call) RunAndReturn(run func(id uuid.UUID) error) *MockSellerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockSellerRepository
func (_mock *MockSellerRepository) FindAll() ([]*entities.Seller, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Seller
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entities.Seller, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entities.Seller); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Seller)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSellerRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockSellerRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockSellerRepository_Expecter) FindAll() *MockSellerRepository_FindAll_Call {
	return &MockSellerRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockSellerRepository_FindAll_Call) Run(run func()) *MockSellerRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSellerRepository_FindAll_Call) Return(sellers []*entities.Seller, err error) *MockSellerRepository_FindAll_Call {
	_c.Call.Return(sellers, err)
	return _c
}

func (_c *MockSellerRepository_FindAll_Call) RunAndReturn(run func() ([]*entities.Seller, error)) *MockSellerRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockSellerRepository
func (_mock *MockSellerRepository) FindById(id uuid.UUID) (*entities.Seller, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.Seller
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*entities.Seller, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *entities.Seller); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Seller)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSellerRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockSellerRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockSellerRepository_Expecter) FindById(id interface{}) *MockSellerRepository_FindById_Call {
	return &MockSellerRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockSellerRepository_FindById_Call) Run(run func(id uuid.UUID)) *MockSellerRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSellerRepository_FindById_Call) Return(seller *entities.Seller, err error) *MockSellerRepository_FindById_Call {
	_c.Call.Return(seller, err)
	return _c
}

func (_c *MockSellerRepository_FindById_Call) RunAndReturn(run func(id uuid.UUID) (*entities.Seller, error)) *MockSellerRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSellerRepository
func (_mock *MockSellerRepository) Update(seller *entities.ValidatedSeller) (*entities.Seller, error) {
	ret := _mock.Called(seller)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Seller
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedSeller) (*entities.Seller, error)); ok {
		return returnFunc(seller)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedSeller) *entities.Seller); ok {
		r0 = returnFunc(seller)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Seller)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.ValidatedSeller) error); ok {
		r1 = returnFunc(seller)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSellerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSellerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - seller *entities.ValidatedSeller
func (_e *MockSellerRepository_Expecter) Update(seller interface{}) *MockSellerRepository_Update_Call {
	return &MockSellerRepository_Update_Call{Call: _e.mock.On("Update", seller)}
}

func (_c *MockSellerRepository_Update_Call) Run(run func(seller *entities.ValidatedSeller)) *MockSellerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.ValidatedSeller
		if args[0] != nil {
			arg0 = args[0].(*entities.ValidatedSeller)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSellerRepository_Update_Call) Return(seller1 *entities.Seller, err error) *MockSellerRepository_Update_Call {
	_c.Call.Return(seller1, err)
	return _c
}

func (_c *MockSellerRepository_Update_Call) RunAndReturn(run func(seller *entities.ValidatedSeller) (*entities.Seller, error)) *MockSellerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
