// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/noellimx/go-ddd/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdempotencyRepository creates a new instance of MockIdempotencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdempotencyRepository is an autogenerated mock type for the IdempotencyRepository type
type MockIdempotencyRepository struct {
	mock.Mock
}

type MockIdempotencyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepository_Expecter {
	return &MockIdempotencyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) Create(ctx context.Context, record *entities.IdempotencyRecord) (*entities.IdempotencyRecord, error) {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.IdempotencyRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.IdempotencyRecord) (*entities.IdempotencyRecord, error)); ok {
		return returnFunc(ctx, record)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.IdempotencyRecord) *entities.IdempotencyRecord); ok {
		r0 = returnFunc(ctx, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.IdempotencyRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.IdempotencyRecord) error); ok {
		r1 = returnFunc(ctx, record)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdempotencyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIdempotencyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - record *entities.IdempotencyRecord
func (_e *MockIdempotencyRepository_Expecter) Create(ctx interface{}, record interface{}) *MockIdempotencyRepository_Create_Call {
	return &MockIdempotencyRepository_Create_Call{Call: _e.mock.On("Create", ctx, record)}
}

func (_c *MockIdempotencyRepository_Create_Call) Run(run func(ctx context.Context, record *entities.IdempotencyRecord)) *MockIdempotencyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.IdempotencyRecord
		if args[1] != nil {
			arg1 = args[1].(*entities.IdempotencyRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_Create_Call) Return(idempotencyRecord *entities.IdempotencyRecord, err error) *MockIdempotencyRepository_Create_Call {
	_c.Call.Return(idempotencyRecord, err)
	return _c
}

func (_c *MockIdempotencyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, record *entities.IdempotencyRecord) (*entities.IdempotencyRecord, error)) *MockIdempotencyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByKey provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) FindByKey(ctx context.Context, key string) (*entities.IdempotencyRecord, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByKey")
	}

	var r0 *entities.IdempotencyRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.IdempotencyRecord, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.IdempotencyRecord); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.IdempotencyRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdempotencyRepository_FindByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByKey'
type MockIdempotencyRepository_FindByKey_Call struct {
	*mock.Call
}

// FindByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIdempotencyRepository_Expecter) FindByKey(ctx interface{}, key interface{}) *MockIdempotencyRepository_FindByKey_Call {
	return &MockIdempotencyRepository_FindByKey_Call{Call: _e.mock.On("FindByKey", ctx, key)}
}

func (_c *MockIdempotencyRepository_FindByKey_Call) Run(run func(ctx context.Context, key string)) *MockIdempotencyRepository_FindByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_FindByKey_Call) Return(idempotencyRecord *entities.IdempotencyRecord, err error) *MockIdempotencyRepository_FindByKey_Call {
	_c.Call.Return(idempotencyRecord, err)
	return _c
}

func (_c *MockIdempotencyRepository_FindByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (*entities.IdempotencyRecord, error)) *MockIdempotencyRepository_FindByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) Update(ctx context.Context, record *entities.IdempotencyRecord) (*entities.IdempotencyRecord, error) {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.IdempotencyRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.IdempotencyRecord) (*entities.IdempotencyRecord, error)); ok {
		return returnFunc(ctx, record)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.IdempotencyRecord) *entities.IdempotencyRecord); ok {
		r0 = returnFunc(ctx, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.IdempotencyRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.IdempotencyRecord) error); ok {
		r1 = returnFunc(ctx, record)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdempotencyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIdempotencyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - record *entities.IdempotencyRecord
func (_e *MockIdempotencyRepository_Expecter) Update(ctx interface{}, record interface{}) *MockIdempotencyRepository_Update_Call {
	return &MockIdempotencyRepository_Update_Call{Call: _e.mock.On("Update", ctx, record)}
}

func (_c *MockIdempotencyRepository_Update_Call) Run(run func(ctx context.Context, record *entities.IdempotencyRecord)) *MockIdempotencyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.IdempotencyRecord
		if args[1] != nil {
			arg1 = args[1].(*entities.IdempotencyRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_Update_Call) Return(idempotencyRecord *entities.IdempotencyRecord, err error) *MockIdempotencyRepository_Update_Call {
	_c.Call.Return(idempotencyRecord, err)
	return _c
}

func (_c *MockIdempotencyRepository_Update_Call) RunAndReturn(run func(ctx context.Context, record *entities.IdempotencyRecord) (*entities.IdempotencyRecord, error)) *MockIdempotencyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
