// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"github.com/google/uuid"
	"github.com/noellimx/go-ddd/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// newTestifyMockProductRepository creates a new instance of testifyMockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTestifyMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *testifyMockProductRepository {
	mock := &testifyMockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// testifyMockProductRepository is an autogenerated mock type for the ProductRepository type
type testifyMockProductRepository struct {
	mock.Mock
}

type testifyMockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *testifyMockProductRepository) EXPECT() *testifyMockProductRepository_Expecter {
	return &testifyMockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type testifyMockProductRepository
func (_mock *testifyMockProductRepository) Create(product *entities.ValidatedProduct) (*entities.Product, error) {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) (*entities.Product, error)); ok {
		return returnFunc(product)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) *entities.Product); ok {
		r0 = returnFunc(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.ValidatedProduct) error); ok {
		r1 = returnFunc(product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// testifyMockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type testifyMockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - product *entities.ValidatedProduct
func (_e *testifyMockProductRepository_Expecter) Create(product interface{}) *testifyMockProductRepository_Create_Call {
	return &testifyMockProductRepository_Create_Call{Call: _e.mock.On("Create", product)}
}

func (_c *testifyMockProductRepository_Create_Call) Run(run func(product *entities.ValidatedProduct)) *testifyMockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.ValidatedProduct
		if args[0] != nil {
			arg0 = args[0].(*entities.ValidatedProduct)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *testifyMockProductRepository_Create_Call) Return(product1 *entities.Product, err error) *testifyMockProductRepository_Create_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *testifyMockProductRepository_Create_Call) RunAndReturn(run func(product *entities.ValidatedProduct) (*entities.Product, error)) *testifyMockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type testifyMockProductRepository
func (_mock *testifyMockProductRepository) Delete(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// testifyMockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type testifyMockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *testifyMockProductRepository_Expecter) Delete(id interface{}) *testifyMockProductRepository_Delete_Call {
	return &testifyMockProductRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *testifyMockProductRepository_Delete_Call) Run(run func(id uuid.UUID)) *testifyMockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *testifyMockProductRepository_Delete_Call) Return(err error) *testifyMockProductRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *testifyMockProductRepository_Delete_Call) RunAndReturn(run func(id uuid.UUID) error) *testifyMockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type testifyMockProductRepository
func (_mock *testifyMockProductRepository) FindAll() ([]*entities.Product, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entities.Product, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entities.Product); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// testifyMockProductRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type testifyMockProductRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *testifyMockProductRepository_Expecter) FindAll() *testifyMockProductRepository_FindAll_Call {
	return &testifyMockProductRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *testifyMockProductRepository_FindAll_Call) Run(run func()) *testifyMockProductRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *testifyMockProductRepository_FindAll_Call) Return(products []*entities.Product, err error) *testifyMockProductRepository_FindAll_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *testifyMockProductRepository_FindAll_Call) RunAndReturn(run func() ([]*entities.Product, error)) *testifyMockProductRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type testifyMockProductRepository
func (_mock *testifyMockProductRepository) FindById(id uuid.UUID) (*entities.Product, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*entities.Product, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *entities.Product); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// testifyMockProductRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type testifyMockProductRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *testifyMockProductRepository_Expecter) FindById(id interface{}) *testifyMockProductRepository_FindById_Call {
	return &testifyMockProductRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *testifyMockProductRepository_FindById_Call) Run(run func(id uuid.UUID)) *testifyMockProductRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *testifyMockProductRepository_FindById_Call) Return(product *entities.Product, err error) *testifyMockProductRepository_FindById_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *testifyMockProductRepository_FindById_Call) RunAndReturn(run func(id uuid.UUID) (*entities.Product, error)) *testifyMockProductRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type testifyMockProductRepository
func (_mock *testifyMockProductRepository) Update(product *entities.ValidatedProduct) (*entities.Product, error) {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) (*entities.Product, error)); ok {
		return returnFunc(product)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.ValidatedProduct) *entities.Product); ok {
		r0 = returnFunc(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.ValidatedProduct) error); ok {
		r1 = returnFunc(product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// testifyMockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type testifyMockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - product *entities.ValidatedProduct
func (_e *testifyMockProductRepository_Expecter) Update(product interface{}) *testifyMockProductRepository_Update_Call {
	return &testifyMockProductRepository_Update_Call{Call: _e.mock.On("Update", product)}
}

func (_c *testifyMockProductRepository_Update_Call) Run(run func(product *entities.ValidatedProduct)) *testifyMockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.ValidatedProduct
		if args[0] != nil {
			arg0 = args[0].(*entities.ValidatedProduct)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *testifyMockProductRepository_Update_Call) Return(product1 *entities.Product, err error) *testifyMockProductRepository_Update_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *testifyMockProductRepository_Update_Call) RunAndReturn(run func(product *entities.ValidatedProduct) (*entities.Product, error)) *testifyMockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
