// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"github.com/noellimx/go-ddd/internal/application/command"
	"github.com/noellimx/go-ddd/internal/application/query"
	mock "github.com/stretchr/testify/mock"
)

// NewTestifyMockProductService creates a new instance of TestifyMockProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestifyMockProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestifyMockProductService {
	mock := &TestifyMockProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TestifyMockProductService is an autogenerated mock type for the ProductService type
type TestifyMockProductService struct {
	mock.Mock
}

type TestifyMockProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *TestifyMockProductService) EXPECT() *TestifyMockProductService_Expecter {
	return &TestifyMockProductService_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type TestifyMockProductService
func (_mock *TestifyMockProductService) CreateProduct(productCommand *command.CreateProductCommand) (*command.CreateProductCommandResult, error) {
	ret := _mock.Called(productCommand)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *command.CreateProductCommandResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*command.CreateProductCommand) (*command.CreateProductCommandResult, error)); ok {
		return returnFunc(productCommand)
	}
	if returnFunc, ok := ret.Get(0).(func(*command.CreateProductCommand) *command.CreateProductCommandResult); ok {
		r0 = returnFunc(productCommand)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.CreateProductCommandResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*command.CreateProductCommand) error); ok {
		r1 = returnFunc(productCommand)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockProductService_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type TestifyMockProductService_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - productCommand *command.CreateProductCommand
func (_e *TestifyMockProductService_Expecter) CreateProduct(productCommand interface{}) *TestifyMockProductService_CreateProduct_Call {
	return &TestifyMockProductService_CreateProduct_Call{Call: _e.mock.On("CreateProduct", productCommand)}
}

func (_c *TestifyMockProductService_CreateProduct_Call) Run(run func(productCommand *command.CreateProductCommand)) *TestifyMockProductService_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *command.CreateProductCommand
		if args[0] != nil {
			arg0 = args[0].(*command.CreateProductCommand)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockProductService_CreateProduct_Call) Return(createProductCommandResult *command.CreateProductCommandResult, err error) *TestifyMockProductService_CreateProduct_Call {
	_c.Call.Return(createProductCommandResult, err)
	return _c
}

func (_c *TestifyMockProductService_CreateProduct_Call) RunAndReturn(run func(productCommand *command.CreateProductCommand) (*command.CreateProductCommandResult, error)) *TestifyMockProductService_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type TestifyMockProductService
func (_mock *TestifyMockProductService) DeleteProduct(productCommand *command.DeleteProductCommand) (*command.DeleteProductCommandResult, error) {
	ret := _mock.Called(productCommand)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 *command.DeleteProductCommandResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*command.DeleteProductCommand) (*command.DeleteProductCommandResult, error)); ok {
		return returnFunc(productCommand)
	}
	if returnFunc, ok := ret.Get(0).(func(*command.DeleteProductCommand) *command.DeleteProductCommandResult); ok {
		r0 = returnFunc(productCommand)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.DeleteProductCommandResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*command.DeleteProductCommand) error); ok {
		r1 = returnFunc(productCommand)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockProductService_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type TestifyMockProductService_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - productCommand *command.DeleteProductCommand
func (_e *TestifyMockProductService_Expecter) DeleteProduct(productCommand interface{}) *TestifyMockProductService_DeleteProduct_Call {
	return &TestifyMockProductService_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", productCommand)}
}

func (_c *TestifyMockProductService_DeleteProduct_Call) Run(run func(productCommand *command.DeleteProductCommand)) *TestifyMockProductService_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *command.DeleteProductCommand
		if args[0] != nil {
			arg0 = args[0].(*command.DeleteProductCommand)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockProductService_DeleteProduct_Call) Return(deleteProductCommandResult *command.DeleteProductCommandResult, err error) *TestifyMockProductService_DeleteProduct_Call {
	_c.Call.Return(deleteProductCommandResult, err)
	return _c
}

func (_c *TestifyMockProductService_DeleteProduct_Call) RunAndReturn(run func(productCommand *command.DeleteProductCommand) (*command.DeleteProductCommandResult, error)) *TestifyMockProductService_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllProducts provides a mock function for the type TestifyMockProductService
func (_mock *TestifyMockProductService) FindAllProducts() (*query.GetAllProductsQueryResult, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllProducts")
	}

	var r0 *query.GetAllProductsQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*query.GetAllProductsQueryResult, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *query.GetAllProductsQueryResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.GetAllProductsQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockProductService_FindAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllProducts'
type TestifyMockProductService_FindAllProducts_Call struct {
	*mock.Call
}

// FindAllProducts is a helper method to define mock.On call
func (_e *TestifyMockProductService_Expecter) FindAllProducts() *TestifyMockProductService_FindAllProducts_Call {
	return &TestifyMockProductService_FindAllProducts_Call{Call: _e.mock.On("FindAllProducts")}
}

func (_c *TestifyMockProductService_FindAllProducts_Call) Run(run func()) *TestifyMockProductService_FindAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TestifyMockProductService_FindAllProducts_Call) Return(getAllProductsQueryResult *query.GetAllProductsQueryResult, err error) *TestifyMockProductService_FindAllProducts_Call {
	_c.Call.Return(getAllProductsQueryResult, err)
	return _c
}

func (_c *TestifyMockProductService_FindAllProducts_Call) RunAndReturn(run func() (*query.GetAllProductsQueryResult, error)) *TestifyMockProductService_FindAllProducts_Call {
	_c.Call.Return(run)
	return _c
}

// FindProductById provides a mock function for the type TestifyMockProductService
func (_mock *TestifyMockProductService) FindProductById(query1 *query.GetProductByIdQuery) (*query.GetProductByIdQueryResult, error) {
	ret := _mock.Called(query1)

	if len(ret) == 0 {
		panic("no return value specified for FindProductById")
	}

	var r0 *query.GetProductByIdQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*query.GetProductByIdQuery) (*query.GetProductByIdQueryResult, error)); ok {
		return returnFunc(query1)
	}
	if returnFunc, ok := ret.Get(0).(func(*query.GetProductByIdQuery) *query.GetProductByIdQueryResult); ok {
		r0 = returnFunc(query1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.GetProductByIdQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*query.GetProductByIdQuery) error); ok {
		r1 = returnFunc(query1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockProductService_FindProductById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProductById'
type TestifyMockProductService_FindProductById_Call struct {
	*mock.Call
}

// FindProductById is a helper method to define mock.On call
//   - query1 *query.GetProductByIdQuery
func (_e *TestifyMockProductService_Expecter) FindProductById(query1 interface{}) *TestifyMockProductService_FindProductById_Call {
	return &TestifyMockProductService_FindProductById_Call{Call: _e.mock.On("FindProductById", query1)}
}

func (_c *TestifyMockProductService_FindProductById_Call) Run(run func(query1 *query.GetProductByIdQuery)) *TestifyMockProductService_FindProductById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *query.GetProductByIdQuery
		if args[0] != nil {
			arg0 = args[0].(*query.GetProductByIdQuery)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockProductService_FindProductById_Call) Return(getProductByIdQueryResult *query.GetProductByIdQueryResult, err error) *TestifyMockProductService_FindProductById_Call {
	_c.Call.Return(getProductByIdQueryResult, err)
	return _c
}

func (_c *TestifyMockProductService_FindProductById_Call) RunAndReturn(run func(query1 *query.GetProductByIdQuery) (*query.GetProductByIdQueryResult, error)) *TestifyMockProductService_FindProductById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function for the type TestifyMockProductService
func (_mock *TestifyMockProductService) UpdateProduct(productCommand *command.UpdateProductCommand) (*command.UpdateProductCommandResult, error) {
	ret := _mock.Called(productCommand)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *command.UpdateProductCommandResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*command.UpdateProductCommand) (*command.UpdateProductCommandResult, error)); ok {
		return returnFunc(productCommand)
	}
	if returnFunc, ok := ret.Get(0).(func(*command.UpdateProductCommand) *command.UpdateProductCommandResult); ok {
		r0 = returnFunc(productCommand)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.UpdateProductCommandResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*command.UpdateProductCommand) error); ok {
		r1 = returnFunc(productCommand)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockProductService_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type TestifyMockProductService_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - productCommand *command.UpdateProductCommand
func (_e *TestifyMockProductService_Expecter) UpdateProduct(productCommand interface{}) *TestifyMockProductService_UpdateProduct_Call {
	return &TestifyMockProductService_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", productCommand)}
}

func (_c *TestifyMockProductService_UpdateProduct_Call) Run(run func(productCommand *command.UpdateProductCommand)) *TestifyMockProductService_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *command.UpdateProductCommand
		if args[0] != nil {
			arg0 = args[0].(*command.UpdateProductCommand)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockProductService_UpdateProduct_Call) Return(updateProductCommandResult *command.UpdateProductCommandResult, err error) *TestifyMockProductService_UpdateProduct_Call {
	_c.Call.Return(updateProductCommandResult, err)
	return _c
}

func (_c *TestifyMockProductService_UpdateProduct_Call) RunAndReturn(run func(productCommand *command.UpdateProductCommand) (*command.UpdateProductCommandResult, error)) *TestifyMockProductService_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}
