// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"github.com/noellimx/go-ddd/internal/application/command"
	"github.com/noellimx/go-ddd/internal/application/query"
	mock "github.com/stretchr/testify/mock"
)

// NewTestifyMockSellerService creates a new instance of TestifyMockSellerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestifyMockSellerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestifyMockSellerService {
	mock := &TestifyMockSellerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TestifyMockSellerService is an autogenerated mock type for the SellerService type
type TestifyMockSellerService struct {
	mock.Mock
}

type TestifyMockSellerService_Expecter struct {
	mock *mock.Mock
}

func (_m *TestifyMockSellerService) EXPECT() *TestifyMockSellerService_Expecter {
	return &TestifyMockSellerService_Expecter{mock: &_m.Mock}
}

// CreateSeller provides a mock function for the type TestifyMockSellerService
func (_mock *TestifyMockSellerService) CreateSeller(sellerCommand *command.CreateSellerCommand) (*command.CreateSellerCommandResult, error) {
	ret := _mock.Called(sellerCommand)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeller")
	}

	var r0 *command.CreateSellerCommandResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*command.CreateSellerCommand) (*command.CreateSellerCommandResult, error)); ok {
		return returnFunc(sellerCommand)
	}
	if returnFunc, ok := ret.Get(0).(func(*command.CreateSellerCommand) *command.CreateSellerCommandResult); ok {
		r0 = returnFunc(sellerCommand)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.CreateSellerCommandResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*command.CreateSellerCommand) error); ok {
		r1 = returnFunc(sellerCommand)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockSellerService_CreateSeller_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeller'
type TestifyMockSellerService_CreateSeller_Call struct {
	*mock.Call
}

// CreateSeller is a helper method to define mock.On call
//   - sellerCommand *command.CreateSellerCommand
func (_e *TestifyMockSellerService_Expecter) CreateSeller(sellerCommand interface{}) *TestifyMockSellerService_CreateSeller_Call {
	return &TestifyMockSellerService_CreateSeller_Call{Call: _e.mock.On("CreateSeller", sellerCommand)}
}

func (_c *TestifyMockSellerService_CreateSeller_Call) Run(run func(sellerCommand *command.CreateSellerCommand)) *TestifyMockSellerService_CreateSeller_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *command.CreateSellerCommand
		if args[0] != nil {
			arg0 = args[0].(*command.CreateSellerCommand)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockSellerService_CreateSeller_Call) Return(createSellerCommandResult *command.CreateSellerCommandResult, err error) *TestifyMockSellerService_CreateSeller_Call {
	_c.Call.Return(createSellerCommandResult, err)
	return _c
}

func (_c *TestifyMockSellerService_CreateSeller_Call) RunAndReturn(run func(sellerCommand *command.CreateSellerCommand) (*command.CreateSellerCommandResult, error)) *TestifyMockSellerService_CreateSeller_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSeller provides a mock function for the type TestifyMockSellerService
func (_mock *TestifyMockSellerService) DeleteSeller(sellerCommand *command.DeleteSellerCommand) (*command.DeleteSellerCommandResult, error) {
	ret := _mock.Called(sellerCommand)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSeller")
	}

	var r0 *command.DeleteSellerCommandResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*command.DeleteSellerCommand) (*command.DeleteSellerCommandResult, error)); ok {
		return returnFunc(sellerCommand)
	}
	if returnFunc, ok := ret.Get(0).(func(*command.DeleteSellerCommand) *command.DeleteSellerCommandResult); ok {
		r0 = returnFunc(sellerCommand)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.DeleteSellerCommandResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*command.DeleteSellerCommand) error); ok {
		r1 = returnFunc(sellerCommand)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockSellerService_DeleteSeller_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSeller'
type TestifyMockSellerService_DeleteSeller_Call struct {
	*mock.Call
}

// DeleteSeller is a helper method to define mock.On call
//   - sellerCommand *command.DeleteSellerCommand
func (_e *TestifyMockSellerService_Expecter) DeleteSeller(sellerCommand interface{}) *TestifyMockSellerService_DeleteSeller_Call {
	return &TestifyMockSellerService_DeleteSeller_Call{Call: _e.mock.On("DeleteSeller", sellerCommand)}
}

func (_c *TestifyMockSellerService_DeleteSeller_Call) Run(run func(sellerCommand *command.DeleteSellerCommand)) *TestifyMockSellerService_DeleteSeller_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *command.DeleteSellerCommand
		if args[0] != nil {
			arg0 = args[0].(*command.DeleteSellerCommand)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockSellerService_DeleteSeller_Call) Return(deleteSellerCommandResult *command.DeleteSellerCommandResult, err error) *TestifyMockSellerService_DeleteSeller_Call {
	_c.Call.Return(deleteSellerCommandResult, err)
	return _c
}

func (_c *TestifyMockSellerService_DeleteSeller_Call) RunAndReturn(run func(sellerCommand *command.DeleteSellerCommand) (*command.DeleteSellerCommandResult, error)) *TestifyMockSellerService_DeleteSeller_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllSellers provides a mock function for the type TestifyMockSellerService
func (_mock *TestifyMockSellerService) FindAllSellers() (*query.GetAllSellersQueryResult, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllSellers")
	}

	var r0 *query.GetAllSellersQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*query.GetAllSellersQueryResult, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *query.GetAllSellersQueryResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.GetAllSellersQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockSellerService_FindAllSellers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllSellers'
type TestifyMockSellerService_FindAllSellers_Call struct {
	*mock.Call
}

// FindAllSellers is a helper method to define mock.On call
func (_e *TestifyMockSellerService_Expecter) FindAllSellers() *TestifyMockSellerService_FindAllSellers_Call {
	return &TestifyMockSellerService_FindAllSellers_Call{Call: _e.mock.On("FindAllSellers")}
}

func (_c *TestifyMockSellerService_FindAllSellers_Call) Run(run func()) *TestifyMockSellerService_FindAllSellers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TestifyMockSellerService_FindAllSellers_Call) Return(getAllSellersQueryResult *query.GetAllSellersQueryResult, err error) *TestifyMockSellerService_FindAllSellers_Call {
	_c.Call.Return(getAllSellersQueryResult, err)
	return _c
}

func (_c *TestifyMockSellerService_FindAllSellers_Call) RunAndReturn(run func() (*query.GetAllSellersQueryResult, error)) *TestifyMockSellerService_FindAllSellers_Call {
	_c.Call.Return(run)
	return _c
}

// FindSellerById provides a mock function for the type TestifyMockSellerService
func (_mock *TestifyMockSellerService) FindSellerById(query1 *query.GetSellerByIdQuery) (*query.GetSellerByIdQueryResult, error) {
	ret := _mock.Called(query1)

	if len(ret) == 0 {
		panic("no return value specified for FindSellerById")
	}

	var r0 *query.GetSellerByIdQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*query.GetSellerByIdQuery) (*query.GetSellerByIdQueryResult, error)); ok {
		return returnFunc(query1)
	}
	if returnFunc, ok := ret.Get(0).(func(*query.GetSellerByIdQuery) *query.GetSellerByIdQueryResult); ok {
		r0 = returnFunc(query1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.GetSellerByIdQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*query.GetSellerByIdQuery) error); ok {
		r1 = returnFunc(query1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockSellerService_FindSellerById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSellerById'
type TestifyMockSellerService_FindSellerById_Call struct {
	*mock.Call
}

// FindSellerById is a helper method to define mock.On call
//   - query1 *query.GetSellerByIdQuery
func (_e *TestifyMockSellerService_Expecter) FindSellerById(query1 interface{}) *TestifyMockSellerService_FindSellerById_Call {
	return &TestifyMockSellerService_FindSellerById_Call{Call: _e.mock.On("FindSellerById", query1)}
}

func (_c *TestifyMockSellerService_FindSellerById_Call) Run(run func(query1 *query.GetSellerByIdQuery)) *TestifyMockSellerService_FindSellerById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *query.GetSellerByIdQuery
		if args[0] != nil {
			arg0 = args[0].(*query.GetSellerByIdQuery)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockSellerService_FindSellerById_Call) Return(getSellerByIdQueryResult *query.GetSellerByIdQueryResult, err error) *TestifyMockSellerService_FindSellerById_Call {
	_c.Call.Return(getSellerByIdQueryResult, err)
	return _c
}

func (_c *TestifyMockSellerService_FindSellerById_Call) RunAndReturn(run func(query1 *query.GetSellerByIdQuery) (*query.GetSellerByIdQueryResult, error)) *TestifyMockSellerService_FindSellerById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSeller provides a mock function for the type TestifyMockSellerService
func (_mock *TestifyMockSellerService) UpdateSeller(updateCommand *command.UpdateSellerCommand) (*command.UpdateSellerCommandResult, error) {
	ret := _mock.Called(updateCommand)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSeller")
	}

	var r0 *command.UpdateSellerCommandResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*command.UpdateSellerCommand) (*command.UpdateSellerCommandResult, error)); ok {
		return returnFunc(updateCommand)
	}
	if returnFunc, ok := ret.Get(0).(func(*command.UpdateSellerCommand) *command.UpdateSellerCommandResult); ok {
		r0 = returnFunc(updateCommand)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.UpdateSellerCommandResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*command.UpdateSellerCommand) error); ok {
		r1 = returnFunc(updateCommand)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TestifyMockSellerService_UpdateSeller_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSeller'
type TestifyMockSellerService_UpdateSeller_Call struct {
	*mock.Call
}

// UpdateSeller is a helper method to define mock.On call
//   - updateCommand *command.UpdateSellerCommand
func (_e *TestifyMockSellerService_Expecter) UpdateSeller(updateCommand interface{}) *TestifyMockSellerService_UpdateSeller_Call {
	return &TestifyMockSellerService_UpdateSeller_Call{Call: _e.mock.On("UpdateSeller", updateCommand)}
}

func (_c *TestifyMockSellerService_UpdateSeller_Call) Run(run func(updateCommand *command.UpdateSellerCommand)) *TestifyMockSellerService_UpdateSeller_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *command.UpdateSellerCommand
		if args[0] != nil {
			arg0 = args[0].(*command.UpdateSellerCommand)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TestifyMockSellerService_UpdateSeller_Call) Return(updateSellerCommandResult *command.UpdateSellerCommandResult, err error) *TestifyMockSellerService_UpdateSeller_Call {
	_c.Call.Return(updateSellerCommandResult, err)
	return _c
}

func (_c *TestifyMockSellerService_UpdateSeller_Call) RunAndReturn(run func(updateCommand *command.UpdateSellerCommand) (*command.UpdateSellerCommandResult, error)) *TestifyMockSellerService_UpdateSeller_Call {
	_c.Call.Return(run)
	return _c
}
